// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'cta__actions': string;
  'cta__btn': string;
  'cta__btn__big': string;
  'cta__btn__close': string;
  'cta__feature': string;
  'cta__feature__content': string;
  'cta__feature__icon': string;
  'cta__main': string;
  'cta__title': string;
}
declare var cssExports: CssExports;
export = cssExports;
