name: Release
on:
  push:
    branches:
      - llp_action_test
jobs:
  release_bin:
    name: Release Binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Git Unshallow
        run: git fetch --prune --unshallow
      - name: Fetch Node Packages
        run: |
          yarn
      - name: Get Release Details
        id: release_details
        uses: botpress/gh-actions/get_release_details@llp_fix_duplicates_in_release_notes
      - name: Fix Change Log
        id: changelog
        run: |
          echo "::set-output name=value::${{ steps.release_details.outputs.changelog }}"
          echo "Is new release?: ${{ steps.release_details.outputs.is_new_release }}"
          echo "Version: ${{ steps.release_details.outputs.version }}"
          echo "Latest Tag: ${{ steps.release_details.outputs.latest_tag }}"
